name: EAS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      # REQUIRED for local Android builds
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      # REQUIRED for local Android builds
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install dependencies
        run: npm ci
        
      - name: Setup EAS CLI
        run: npm install -g eas-cli
        
      - name: Create .env file
        run: |
          touch .env
          echo "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" >> .env
          echo "EXPO_PUBLIC_OUTDRINKME_API_URL=${{ secrets.EXPO_PUBLIC_OUTDRINKME_API_URL }}" >> .env
          
      - name: Authenticate with EAS
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
      # Download keystore from EAS to use locally
      - name: Download credentials from EAS
        run: |
          mkdir -p credentials/android
          eas credentials --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
      # Build locally using EAS (which will use downloaded credentials)
      - name: Build Android AAB locally
        run: eas build --platform android --profile production --local --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: android-release-aab
          path: '**/*.aab'
          retention-days: 30